service: testhttp
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:215885706118:table/usersTable

plugins:
  - serverless-auto-swagger


functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  createUser:
    handler: src/services/users/handlers/createUser.handler
    events:
      - httpApi:
          path: /user/create
          method: post
          bodyType: ICreateUser
  getUsers:
    handler: src/services/users/handlers/getUsers.handler
    events:
      - httpApi:
          path: /users
          method: get
  getFilms:
    handler: src/services/films/handlers/getFilms.handler
    events:
      - httpApi:
          path: /films
          method: get


resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH