// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "testhttp",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "api",
        "description": "",
        "operationId": "api.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/user/create": {
      "post": {
        "summary": "createUser",
        "description": "",
        "operationId": "createUser.post./user/create",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ICreateUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "getUsers",
        "description": "",
        "operationId": "getUsers.get./users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/films": {
      "get": {
        "summary": "getFilms",
        "description": "",
        "operationId": "getFilms.get./films",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "ICreateUser": {
      "properties": {
        "nombre": {
          "title": "ICreateUser.nombre",
          "type": "string"
        },
        "altura": {
          "title": "ICreateUser.altura",
          "type": "string"
        },
        "ojo_color": {
          "title": "ICreateUser.ojo_color",
          "type": "string"
        },
        "pelo_color": {
          "title": "ICreateUser.pelo_color",
          "type": "string"
        },
        "peso": {
          "title": "ICreateUser.peso",
          "type": "string"
        },
        "piel_color": {
          "title": "ICreateUser.piel_color",
          "type": "string"
        },
        "nacimiento_anio": {
          "title": "ICreateUser.nacimiento_anio",
          "type": "string"
        },
        "genero": {
          "title": "ICreateUser.genero",
          "type": "string"
        },
        "vehiculos": {
          "items": {
            "title": "ICreateUser.vehiculos.[]",
            "type": "string"
          },
          "title": "ICreateUser.vehiculos",
          "type": "array"
        }
      },
      "required": [
        "nombre",
        "altura",
        "ojo_color",
        "pelo_color",
        "peso",
        "piel_color",
        "nacimiento_anio",
        "genero",
        "vehiculos"
      ],
      "additionalProperties": false,
      "title": "ICreateUser",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};